### PR TITLE
build: add go build tag to exclude DTO validator

### PR DESCRIPTION
**Pull request by hahattan**
Signed-off-by: Chris Hung <chris@iotechsys.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) N/A
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) N/A
  <link to docs PR>

## Testing Instructions

1. replace go-mod-core-contracts with this branch
2. update go build tags to include `no_dto_validator`
3. memory footprint reduce ~2MB

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@cloudxxx8 , why was this needed?

**Comment by cloudxxx8** [comment]
When we are implementing a new services for EdgeX, we always want to use the `go-mod-bootstrap` for the consistence.
However, `go-mod-bootstrap` contains `go-mod-core-contracts` and it contains `go-playground/validator`
`go-playground/validator` is needless for the services without using DTOs.  By adding `no_dto_validator` in this way, the service memory consumption can reduce 2 MB, and it won't impact the existing services.

**Comment by lenny-intel** [comment]
Got it! Thanks!

**Pull request merged**
