### PR TITLE
Feat (core-data): Event ID has to be UUID and pre-populated

### LINKED ISSUE #287: Pre-populate the event ID with a UUID
copied the description from related to https://github.com/edgexfoundry/edgex-go/issues/2684
we need to start from the modification in contracts

# 🚀 Feature Request
Make ID field of event required and provided before passing to core data for persistence.

### Relevant Package
core data and core contracts

### Description
This feature began as an ADR (see https://github.com/edgexfoundry/edgex-docs/pull/227).  Per the discussion, the idea is to 
generate a UUID and assign it to the id field before storing the event to the database. If the id field was empty at the time of persistence, then have core data generate a UUID (or just have the ID field as required making clients provide the UUID in the ID).

Per @lenny-intel - this also solves why we used checksum in the first place for CBOR encoded events. Now the ID will be set in the CBOR encoded Event and accessible in App Service once it is un-marshaled. Then we only need to have the MarkAsPushedById API.

### PR DESCRIPTION
**Pull request by cloudxxx8**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Event ID can be empty before sending to core-data and assigned in core-data

Issue Number: Fix #287 

## What is the new behavior?
Validate Event ID is an UUID and pre-populated

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
No

## Are there any specific instructions or things that should be known prior to reviewing?
No

### CODE REVIEW

**Review by lenny-intel — COMMENTED** [review]
LGTM, but do we also need to do the same for Reading Id?

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
> LGTM, but do we also need to do the same for Reading Id?

no, I don't think so.  the purpose of this design is to replace checksum for "pushed" API.
I can't think out any advantage to do the same in Reading.

**Comment by lenny-intel** [comment]
> I can't think out any advantage to do the same in Reading.

If core data doesn't persist or is bypassed then the reading ID is never set.

**Comment by cloudxxx8** [comment]
reading ID is for database identification.  if readings are not persisted, they will always with Event, and ID is not a matter.

**Comment by lenny-intel** [comment]
> ID is not a matter.

Ok, ya sold me. ;-)

**Review by lenny-intel — APPROVED** [review]

**Pull request merged**
