### PR TITLE
feat: Add new API route constants for Echo

### LINKED ISSUE #845: Add new API route constants with path params for Echo
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 
This feature request is for all of the EdgeX micro services have a dependency on it.

### Description [**REQUIRED**]
 
The original `gorilla/mux` package uses the following format to define the URL path with parameters:
```
/api/v3/device/name/{name}
```

However, the `Echo` [package](https://echo.labstack.com/)(the replacement of `gorilla/mux`) uses a different format as below:
```
/api/v3/device/name/:name
```
### Describe the solution you'd like

New constants are added in `echo_api_constants.go` to define the new API route constants with URL path parameters.

### PR DESCRIPTION
**Pull request by lindseysimple**
Closes #845. Add new API route constants with path params for Echo.

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
Why did we create new constants rather than simply adjusting the existing ones?
Using the `echo` package name in the constant is not good practice.

**Comment by cloudxxx8** [comment]
The original ones are public constants, and they may be used by other projects with gorilla, such as eKuiper or any rest clients.
It's breaking changes.
The idea is to use the original constants name in v4 and remove those temporary echo ones.
I didn't notice the path param declaration is quite different.

**Comment by lenny-intel** [comment]
OK, so please add comment that these will be removed in v4

**Pull request merged**
