### PR TITLE
feat(security): Enable gosec and default linter set

### LINKED ISSUE #667: Add "make lint" target and add to "make test" target
Should enable golangci-lint with default linters + gosec.

See https://github.com/edgexfoundry/edgex-go/issues/3565

### PR DESCRIPTION
**Pull request by bnevis-i**
Fixes #667

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) N/A
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?) Yes
- [ ] I have opened a PR for the related docs change (if not, why?)
N/A

## Testing Instructions
```make test```

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@bnevis-i please help resolve this build issue

[2022-01-06T04:42:45.515Z] clients/logger/logger.go:31:2: SA1019: package github.com/go-kit/kit/log is deprecated: Use github.com/go-kit/log instead. (staticcheck)
[2022-01-06T04:42:45.515Z] 	"github.com/go-kit/kit/log"
[2022-01-06T04:42:45.515Z] 	^
[2022-01-06T04:42:45.515Z] make: *** [Makefile:13: lint] Error 1

**Comment by bnevis-i** [comment]
@cloudxxx8  I'm on it.

**Comment by bnevis-i** [comment]
@cloudxxx8 Resolved.

**Review by weichou1229 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
