### PR TITLE
feat(V2): Add factory methods for DeviceProfileRequest DTO

### LINKED ISSUE #477: [V2] Create factory methods for DeviceProfileRequest DTO
These factory methods make the creation of DeviceProfileRequest for developers.

### PR DESCRIPTION
**Pull request by weichou1229**
Close #477

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## What is the new behavior?
Add factory methods for DeviceProfileRequest DTO

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by weichou1229** [comment]
I didn't create factory methods for sub object DeviceResources, DeviceCommands, CoreCommands because the they haven't API version field and doesn't provide API for querying.

**Comment by lenny-intel** [comment]
> I didn't create factory methods for sub object such as, DeviceResources, DeviceCommands, and CoreCommands ,because they don't have API version field and provide API for querying.

@weichou1229 , IMO the factory methods for DeviceResources, DeviceCommands, and CoreCommands are still useful for usability, consistency and completeness.

**Review by lenny-intel — DISMISSED** [review]
LGTM

**Comment by cloudxxx8** [comment]
@lenny-intel We need more discussion for this, maybe in the WG meeting.  
IMHO, there is no fields needing auto-filled in those sub objects, and we have third and forth levels sub-objects.  We would need to create endless factory method which might not be used.

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
@lenny-intel in the second thought.  the original proposal by @weichou1229 might be better.
In Device Service, it would load the full JSON, TOML, or YAML to create a request DTO.  It could be troublesome if we create a DTO with name and then set up each field one by one.  What do you think?

```
func NewAddDeviceRequest(name string) AddDeviceRequest {
	return AddDeviceRequest{
		BaseRequest: common.NewBaseRequest(),
		Device:       dtos.NewDevice(name),
	}
}

func NewDevice(name string) Device {
	return Device{
		Versionable: common.NewVersionable(),
		Id:                uuid.NewString(),
                Name:          name,
	}
}
```

**Comment by lenny-intel** [comment]
> In Device Service, it would load the full JSON, TOML, or YAML to create a request DTO. It could be troublesome if we create a DTO with name and then set up each field one by one. What do you think?

@cloudxxx8 , I think you mean Device Profile, but yes that would be troublesome unless the factory method did the load of the full JSON, TOML, or YAML. I.e. passed the location as a parameter.

**Comment by lenny-intel** [comment]
> IMHO, there is no fields needing auto-filled in those sub objects

@cloudxxx8 , agreed now since the profiles are `loaded`. THX!

**Comment by weichou1229** [comment]
Modified factory method to use the full device profile DTO instead of the name.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
