### PR TITLE
feat(v2): Update DeviceServiceCommandClient interface to have queryParams

### LINKED ISSUE #485: [V2] Update DeviceServiceCommandClient interface to have queryParams
The current `DeviceServiceCommandClient` interface only specify `pushEvent` and `returnEvent` as part of func `GetCommand` signature, which is not properly handling user specified query parameters.  The `DeviceServiceCommandClient` interface shall update its `GetCommand` signature to have `queryParams` so that all query params could be passed to device service for further processing.

### PR DESCRIPTION
**Pull request by judehung**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## Issue Number:
fix #485 

## What is the new behavior?
The current DeviceServicCommandClient interface only specify pushEvent and returnEvent as part of func GetCommand signature, which is not properly handling user specified query parameters. The DeviceServicCommandClient interface shall update its GetCommand signature to have queryParams so that all query params could be passed to device service for further processing.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
Please do the same for the Set command.  It might be useful in the future.

**Comment by judehung** [comment]
> Please do the same for the Set command. It might be useful in the future.

@cloudxxx8 for PUT request, the device sdk only consumed BODY and our common client library also don't deal with query strings, do we really need to do this for Set command?

**Comment by cloudxxx8** [comment]
> > Please do the same for the Set command. It might be useful in the future.
> 
> @cloudxxx8 for PUT request, the device sdk only consumed BODY and our common client library also doesn't deal with query strings, do we really need to do this for Set command?

That's for now.  We might use query parameters in the future, so I thought Command Service should pass all parameters anyway.

**Comment by judehung** [comment]
Okay, although it's still awkward to me for a Put request to consume both Body and query strings, https://github.com/edgexfoundry/go-mod-core-contracts/pull/486/commits/c9200ddc3879e5410f65c374f071ff81d8945aac updates the `SetCommand` func with queryParams as parameters.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
