### PR TITLE
feat: Implement the re-designed device profile model

### LINKED ISSUE #539: [V2] Implement the re-designed device profile model
- coreCommands is dropped from the device profile

- An attribute (isHidden: true/false with false the default) will be added to the deviceResource and deviceCommand elements to indicate the visibility of any resource or command via Core Command (effectively replacing the coreCommands section of the profile).

- On deviceCommands, we are removing the get/set section.

- On deviceCommands, we are renaming parameter to defaultValue

- On deviceCommands, we will use single resourceOperations to specify selected deviceResources on deviceCommands.

- On deviceCommands, add a **readWrite** indicator to show whether get or set for the deviceCommand is allowed.  The readWrite property can be more restrictive than the associated readWrite property for the deviceResource but it cannot reverse or relax the restriction of the deviceResource (example, make a deviceCommand ‘R’ when the deviceResource is ‘W’ or make the deviceCommand ‘RW’ when the deviceResource is ‘W’). From a schema perspective, the readWrite indicator will **align to what is already the readWrite property on deviceResource**.

- A sourceName will be added to Event DTO to specify the deviceResource or deviceCommand.  The sourceName property will also be used in AutoEvents.

### PR DESCRIPTION
**Pull request by weichou1229**
Close #539

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/.github/Contributing.md.

## What is the new behavior?
Implement the re-designed device profile model

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by lenny-intel — DISMISSED** [review]
LGTM

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
add omitempty to IsHidden for both json and yaml

**Comment by weichou1229** [comment]
Added the omitempty to IsHidden.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
