### PR TITLE
docs: Remove docs in V2 model and link to swagger

### PR DESCRIPTION
**Pull request by cloudxxx8**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?
There are some inconsistent docs in V2 model and dto

## Issue Number:
Fix https://github.com/edgexfoundry/go-mod-core-contracts/issues/309

## What is the new behavior?
We point to SwaggerHub which is the API documentation.  We will use the single of
source for the documentation.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by lenny-intel — CHANGES_REQUESTED** [review]
I am good with the link to swagger for the DTOs, but not for the models. The swagger documents the DTOs, not the model's.

**Comment by cloudxxx8** [comment]
@lenny-intel that's the original discussion in the #309, and I mean model in that PR.
Should we copy all the same description to the model package?  So far, they are the same.
My suggestion is to link to the swagger file and write own the comment for the difference only.

**Comment by lenny-intel** [comment]
> My suggestion is to link to the swagger file and write own the comment for the difference only.

I am ok with that approach if we add the comment for each model like:
`Model fields are same as the DTOs documented by this swagger. Exceptions, if any, are noted below.`

**Comment by cloudxxx8** [comment]
> > My suggestion is to link to the swagger file and write own the comment for the difference only.
> 
> I am ok with that approach if we add the comment for each model like:
> `Model fields are same as the DTOs documented by this swagger. Exceptions, if any, are noted below.`

added

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
