### PR TITLE
fix(v2dto):Remove validate call in add request DTO 

### LINKED ISSUE #306: V2 DTO AddRequests UnmarshalJSON() should not execute Validate()
According to the V2 API design, Add and Update related requests are arrays of requests, and it should still process all the requests if some of the request cannot pass the validation.  
In the current implementation, unmarshal the request array would validate all of the requests and return the error even if some of the requests are valid.
The `Validate()` func should be invoked by the Controller in edgex-go individually.

### PR DESCRIPTION
**Pull request by cloudxxx8**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Fix #306

## What is the new behavior?
In V2 API design, all the add request would be in array form when
calling add APIs.  Thus, the requests should be validated
individually, not in the UnmarshalJSON func.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by lenny-intel — COMMENTED** [review]
Another option would be for these functions to return []error and have them iterate over the requests to validate each one and build the slice. This would keep validation in the DTO, rather than push it to the Controllers.

**Review by lenny-intel — COMMENTED** [review]
The controllers would have to change to call theses functions directly.

**Comment by cloudxxx8** [comment]
> Another option would be for these functions to return []error and have them iterate over the requests to validate each one and build the slice. This would keep validation in the DTO, rather than push it to the Controllers.

it won't work because the DTO is a single request, not an array of requests.
unless we create another DTO to contain an array of add requests

**Comment by lenny-intel** [comment]
> it won't work because the DTO is a single request, not an array of requests.
@cloudxxx8 Right, I meant to iterate over the array of profiles in the request. We still need to validate the BaseRequest. The reason I would like to keep the validation here is so that it is done for any protocol. If moved to the HTTP Controller, we then have to repeat the validation in future protocol controllers.

Other thought I have is yes, we handle multiple profiles but the validation is for the whole request. I.e. we can handle errors processing individual profiles and report back status for each, but the request as a whole needs to be valid.

**Comment by lenny-intel** [comment]
@cloudxxx8 , after further review I don't agree with removing the validation here. Good topic for tomorrows Core WG.

**Pull request closed without merging**
