### PR TITLE
feat: add ProtocolPropertiesRequest for validate API

### PR DESCRIPTION
**Pull request by hahattan**
Signed-off-by: Chris Hung <chris@iotechsys.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) N/A
  <link to docs PR>

### CODE REVIEW

**Comment by lenny-intel** [comment]
@hahattan , why is this needed? I thought that the new device would be sent to the Validate endpoint which would validate the ProtocolProperties

**Comment by hahattan** [comment]
> @hahattan , why is this needed? I thought that the new device DTO would be sent to the Validate endpoint which would validate the ProtocolProperties

I thought we're only sending the `Protocols` field in device DTO .
This is unnecessary if we're sending device DTO, if that's the case we can close this PR and I'll make change in SDK interface.

**Comment by lenny-intel** [comment]
> I thought we're only sending the `Protocols` field in device DTO .

Seems sending the Device DTO simplifies it so we don't have to add this code and opens it up to other validation beyond protocols if ever needed. @cloudxxx8 thoughts?

**Comment by cloudxxx8** [comment]
@hahattan @lenny-intel since the Device DTO is relative small, it would be fine send out the whole Device DTO to validate.
On the other hand, the Device can log the device name or other information for debugging.

@hahattan however, it's good you catch some typo.  Could you please open another PR for the go doc typo and unit test correction?  thanks.

**Comment by hahattan** [comment]
last question: 
per the discussion in https://github.com/edgexfoundry/device-sdk-go/pull/1097#issuecomment-1040587647
I think I should use `AddDeviceRequest` right ? (although the naming is confusing in SDK side)
https://github.com/edgexfoundry/go-mod-core-contracts/blob/58b8b4bc41ce6f7a1dbe3f3412e4301586b7a828/dtos/requests/device.go#L21-L24

**Comment by cloudxxx8** [comment]
Yes, let's reuse it to simplify the contract

**Comment by cloudxxx8** [comment]
If this happens in Update calls and it contains the request contains protocolProperties changes, we will use UpdateDeviceRequest to avoid confusion.  It should contain the full protocolProperties anyway. 
https://github.com/edgexfoundry/go-mod-core-contracts/blob/58b8b4bc41ce6f7a1dbe3f3412e4301586b7a828/dtos/requests/device.go#L63-L66

**Pull request closed without merging**
