### PR TITLE
models.profile json/yaml unmarshal

### PR DESCRIPTION
**Pull request by q974259836**
devcie service sdk:  'service. Runningservice(). Adddeviceprofile' 
```
profile := models.DeviceProfile{}
err = yaml.Unmarshal([]byte(Profile), &profile)
// ...
id, err := service.RunningService().AddDeviceProfile(profile)
```

### CODE REVIEW

**Review by cloudxxx8 — COMMENTED** [review]
please don't use comment.  just remove all of them,  thanks for taking care of this.

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
sorry, I just noticed you are modifying model package.
we don't need to marshal or unmarshal the struct in this package.  all the passing struct are using the ones in dto package.  may I know why you want to make this change?

**Comment by cloudxxx8** [comment]
by the way, please follow the committing code guideline.  open an issue to describe your problem first.
https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines

**Comment by cloudxxx8** [comment]
use `profile := dtos.DeviceProfile{}`

**Comment by q974259836** [comment]
I tried to use this function to add a profile:
```
func (s *DeviceService) AddDeviceProfile(profile models.DeviceProfile) (string, error) {..}
```
> sorry, I just noticed you are modifying `model` package.
> we don't need to marshal or unmarshal the struct in this package. all the passing struct are using the ones in `dtos` package. may I know why you want to make this change?

**Comment by weichou1229** [comment]
You should Unmarshal with profile DTO and convert to model like the following code snippet:
```
	dto := dtos.DeviceProfile{}
	err := yaml.Unmarshal([]byte(""), &dto)
	// ...
	model := dtos.ToDeviceProfileModel(dto)
	id, err := service.RunningService().AddDeviceProfile(model)
```

**Comment by q974259836** [comment]
> You should Unmarshal with profile DTO and convert to model like the following code snippet:
> 
> ```
> 	dto := dtos.DeviceProfile{}
> 	err := yaml.Unmarshal([]byte(""), &dto)
> 	// ...
> 	model := dtos.ToDeviceProfileModel(dto)
> 	id, err := service.RunningService().AddDeviceProfile(model)
> ```

Get it ! Thank you so much.

**Pull request closed without merging**
